<?php

/**
 * This is the model base class for the table "student".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Student".
 *
 * Columns in table "student" available as properties of the model,
 * followed by relations of table "student" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $age
 *
 * @property Scard[] $scards
 */
abstract class BaseStudent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'student';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Student|Students', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, age', 'required'),
			array('age', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('id, name, age', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'scards' => array(self::HAS_MANY, 'Scard', 'student_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'age' => Yii::t('app', 'Age'),
			'scards' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('age', $this->age);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}